In [323]:
import numpy as np
import pandas as pd
from keras.preprocessing.image import ImageDataGenerator
import os
import random 
import cv2
import imutils
import random
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelBinarizer
from keras.utils import np_utils
from keras.models import Sequential
from keras import optimizers
from sklearn.preprocessing import LabelBinarizer
from keras import backend as K
from keras.layers import Dense, Activation, Flatten, Dense,MaxPooling2D, Dropout
from keras.layers import Conv2D, MaxPooling2D, BatchNormalization

In [324]:
dir = "D:\ML\ML_AI_Project_4th-year\images"
train_data = []
val_data = []
test_Data=[]
img_size = 28
for i in os.listdir(dir):
    print(i)

    count = 0
    sub_directory = os.path.join(dir,i)
    for j in os.listdir(sub_directory):
        count+=1
        if count %10==5 or count %10==7:          
            img = cv2.imread(os.path.join(sub_directory,j),0)
            img = cv2.resize(img,(img_size,img_size))
            val_data.append([img,i])
        elif count %9==0:          
            img = cv2.imread(os.path.join(sub_directory,j),0)
            img = cv2.resize(img,(img_size,img_size))
            test_Data.append([img,i])
        else:
            img = cv2.imread(os.path.join(sub_directory,j),0)
            img = cv2.resize(img,(img_size,img_size))
            train_data.append([img,i])
            



0
1
2


In [325]:
print(len(val_data))
print(len(train_data))
print(len(test_Data))

296
1054
128


In [326]:
random.shuffle(train_data)
random.shuffle(val_data)
random.shuffle(test_Data)

In [327]:
train_X = []
train_Y = []
for features,label in train_data:
    train_X.append(features)
    train_Y.append(label)
# print(train_X)



In [328]:
val_X = []
val_Y = []
for features,label in val_data:
    val_X.append(features)
    val_Y.append(label)

In [329]:
test_X=[]
test_Y=[]
for features,label in val_data:
    test_X.append(features)
    test_Y.append(label)


In [330]:
LB = LabelBinarizer()
train_Y = LB.fit_transform(train_Y)
val_Y = LB.fit_transform(val_Y)
test_Y= LB.fit_transform(test_Y)


In [331]:
train_X = np.array(train_X)/255.0
train_X = train_X.reshape(-1,28,28,1)
train_Y = np.array(train_Y)
print(train_Y)
print(train_X)

[[0 1 0]
 [0 1 0]
 [0 0 1]
 ...
 [0 0 1]
 [0 1 0]
 [0 1 0]]
[[[[0.41176471]
   [0.32156863]
   [0.32156863]
   ...
   [0.37254902]
   [0.38823529]
   [0.70588235]]

  [[0.36862745]
   [0.34509804]
   [0.34117647]
   ...
   [0.34901961]
   [0.4       ]
   [0.67843137]]

  [[0.37647059]
   [0.34509804]
   [0.3372549 ]
   ...
   [0.35294118]
   [0.36862745]
   [0.65098039]]

  ...

  [[0.61176471]
   [0.74117647]
   [0.58823529]
   ...
   [0.41176471]
   [0.5254902 ]
   [0.78431373]]

  [[0.62352941]
   [0.65882353]
   [0.6627451 ]
   ...
   [0.38823529]
   [0.6627451 ]
   [0.7372549 ]]

  [[0.72941176]
   [0.74117647]
   [0.62352941]
   ...
   [0.43921569]
   [0.54509804]
   [0.70980392]]]


 [[[0.39607843]
   [0.34117647]
   [0.32156863]
   ...
   [0.36862745]
   [0.6745098 ]
   [0.68627451]]

  [[0.35686275]
   [0.32941176]
   [0.30980392]
   ...
   [0.37254902]
   [0.50588235]
   [0.67843137]]

  [[0.38039216]
   [0.32941176]
   [0.3254902 ]
   ...
   [0.37254902]
   [0.39215686]
   [

In [332]:


val_X = np.array(val_X)/255.0
val_X = val_X.reshape(-1,28,28,1)
val_Y = np.array(val_Y)

In [333]:
test_X = np.array(test_X)/255.0
test_X = val_X.reshape(-1,28,28,1)
test_Y = np.array(test_Y)

In [334]:
print(train_X.shape,val_X.shape,test_X)
print(train_Y.shape,val_Y.shape,test_X)

(1054, 28, 28, 1) (296, 28, 28, 1) [[[[0.45882353]
   [0.44705882]
   [0.4       ]
   ...
   [0.80392157]
   [0.89411765]
   [0.98823529]]

  [[0.43137255]
   [0.42745098]
   [0.39215686]
   ...
   [0.77647059]
   [0.86666667]
   [0.98823529]]

  [[0.4       ]
   [0.40784314]
   [0.39215686]
   ...
   [0.75294118]
   [0.85882353]
   [0.90980392]]

  ...

  [[0.5254902 ]
   [0.48627451]
   [0.4627451 ]
   ...
   [0.45490196]
   [0.51764706]
   [0.50196078]]

  [[0.53333333]
   [0.49411765]
   [0.47058824]
   ...
   [0.50588235]
   [0.5372549 ]
   [0.55294118]]

  [[0.54901961]
   [0.51372549]
   [0.49803922]
   ...
   [0.57647059]
   [0.54901961]
   [0.61960784]]]


 [[[0.60392157]
   [0.58431373]
   [0.54901961]
   ...
   [0.52941176]
   [0.54509804]
   [0.58431373]]

  [[0.6       ]
   [0.58431373]
   [0.56470588]
   ...
   [0.52156863]
   [0.55686275]
   [0.58823529]]

  [[0.69803922]
   [0.55686275]
   [0.56862745]
   ...
   [0.54509804]
   [0.56078431]
   [0.58039216]]

  ...

  [[

In [335]:


model = Sequential()

model.add(Conv2D(32, (3, 3), padding = "same", activation='relu', input_shape=(28,28,1)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))
 
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3, activation='softmax'))



In [336]:
model.summary()

Model: "sequential_18"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_54 (Conv2D)          (None, 28, 28, 32)        320       
                                                                 
 max_pooling2d_54 (MaxPoolin  (None, 14, 14, 32)       0         
 g2D)                                                            
                                                                 
 conv2d_55 (Conv2D)          (None, 12, 12, 64)        18496     
                                                                 
 max_pooling2d_55 (MaxPoolin  (None, 6, 6, 64)         0         
 g2D)                                                            
                                                                 
 conv2d_56 (Conv2D)          (None, 4, 4, 128)         73856     
                                                                 
 max_pooling2d_56 (MaxPoolin  (None, 2, 2, 128)      

In [337]:
model.compile(loss='categorical_crossentropy', optimizer="adam",metrics=['accuracy'])

In [338]:
history = model.fit(train_X,train_Y, epochs=50, batch_size=32, validation_data = (val_X, val_Y),  verbose=1)

Epoch 1/50
33/33 [==============================] - 4s 52ms/step - loss: 0.9913 - accuracy: 0.4772 - val_loss: 0.5971 - val_accuracy: 0.6791
Epoch 2/50
33/33 [==============================] - 1s 36ms/step - loss: 0.4087 - accuracy: 0.8558 - val_loss: 0.1668 - val_accuracy: 0.9527
Epoch 3/50
33/33 [==============================] - 1s 42ms/step - loss: 0.1223 - accuracy: 0.9725 - val_loss: 0.0466 - val_accuracy: 0.9865
Epoch 4/50
33/33 [==============================] - 1s 39ms/step - loss: 0.0501 - accuracy: 0.9877 - val_loss: 0.0256 - val_accuracy: 1.0000
Epoch 5/50
33/33 [==============================] - 1s 32ms/step - loss: 0.0210 - accuracy: 0.9943 - val_loss: 0.0165 - val_accuracy: 1.0000
Epoch 6/50
33/33 [==============================] - 1s 40ms/step - loss: 0.0166 - accuracy: 0.9962 - val_loss: 0.0064 - val_accuracy: 1.0000
Epoch 7/50
33/33 [==============================] - 1s 38ms/step - loss: 0.0151 - accuracy: 0.9981 - val_loss: 0.0038 - val_accuracy: 1.0000
Epoch 8/50
33

In [339]:
model.save('modelss/models.h5')

In [340]:
# img = cv2.imread('D:\ML\ML_AI_Project_4th-year\images\1\11.jpg',0)
# img = cv2.resize(img,(28,28))

In [342]:
prediction=model.predict(test_X)
for i in range(100):
    
    print(prediction[i])
    print(test_Y[i])
    probabilityValue=np.amax(prediction[i])
    print(probabilityValue*100)

10/10 [==============================] - 0s 7ms/step
[9.9999976e-01 1.7882233e-07 2.1766795e-09]
[1 0 0]
99.99997615814209
[2.0085156e-06 6.0136601e-10 9.9999797e-01]
[0 0 1]
99.99979734420776
[7.2305497e-08 9.9999988e-01 3.2767292e-11]
[0 1 0]
99.99998807907104
[2.7083395e-08 1.0000000e+00 8.8732632e-11]
[0 1 0]
100.0
[1.0063948e-07 9.9999988e-01 3.5013265e-10]
[0 1 0]
99.99998807907104
[9.9999988e-01 1.7429323e-07 1.5920252e-09]
[1 0 0]
99.99998807907104
[9.9999928e-01 6.6084499e-07 2.4765939e-08]
[1 0 0]
99.99992847442627
[9.9999988e-01 1.4675422e-07 7.7885698e-09]
[1 0 0]
99.99998807907104
[1.000000e+00 4.537986e-08 3.060002e-08]
[1 0 0]
100.0
[6.977146e-08 2.500657e-11 9.999999e-01]
[0 0 1]
99.99998807907104
[7.7469117e-08 2.7727147e-11 9.9999988e-01]
[0 0 1]
99.99998807907104
[2.5469005e-08 1.0000000e+00 3.9884474e-11]
[0 1 0]
100.0
[2.6087859e-08 1.0000000e+00 7.1878718e-11]
[0 1 0]
100.0
[1.2320206e-07 4.5835519e-11 9.9999988e-01]
[0 0 1]
99.99998807907104
[5.522325e-07 9.99999

In [ ]:
def process(imgg):
    imgg = cv2.resize(imgg,(28,28))
    test_x=[]
    test_x.append(imgg)
    test_x = np.array(test_x)/255.0
    test_x = test_x.reshape(-1,28,28,1)
    prediction=model.predict_classes(test_x)
    prob=np.amax(predictions[i])
    print(prob*100)
    print(prediction)
    return prediction

    