In [41]:
import numpy as np
import pandas as pd
from keras.preprocessing.image import ImageDataGenerator
import os
import random 
import cv2
import imutils
import random
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelBinarizer
from keras.utils import np_utils
from keras.models import Sequential
from keras import optimizers
from sklearn.preprocessing import LabelBinarizer
from keras import backend as K
from keras.layers import Dense, Activation, Flatten, Dense,MaxPooling2D, Dropout
from keras.layers import Conv2D, MaxPooling2D, BatchNormalization

In [42]:
dir = "D:\ML\ML_project_final\images\interview"
train_data = []
val_data = []
test_Data=[]
img_size = 28
for i in os.listdir(dir):
    print(i)

    count = 0
    sub_directory = os.path.join(dir,i)
    for j in os.listdir(sub_directory):
        count+=1
        if count %10==5 or count %10==7:          
            img = cv2.imread(os.path.join(sub_directory,j),0)
            img = cv2.resize(img,(img_size,img_size))
            val_data.append([img,i])
        elif count %9==0:          
            img = cv2.imread(os.path.join(sub_directory,j),0)
            img = cv2.resize(img,(img_size,img_size))
            test_Data.append([img,i])
        else:
            img = cv2.imread(os.path.join(sub_directory,j),0)
            img = cv2.resize(img,(img_size,img_size))
            train_data.append([img,i])
            



0
1
2


In [43]:
print(len(val_data))
print(len(train_data))
print(len(test_Data))

3237
11511
1436


In [44]:
random.shuffle(train_data)
random.shuffle(val_data)
random.shuffle(test_Data)

In [45]:
train_X = []
train_Y = []
for features,label in train_data:
    train_X.append(features)
    train_Y.append(label)



In [46]:
val_X = []
val_Y = []
for features,label in val_data:
    val_X.append(features)
    val_Y.append(label)

In [47]:
test_X=[]
test_Y=[]
for features,label in val_data:
    test_X.append(features)
    test_Y.append(label)


In [48]:
LB = LabelBinarizer()
train_Y = LB.fit_transform(train_Y)
val_Y = LB.fit_transform(val_Y)
test_Y= LB.fit_transform(test_Y)


In [49]:
train_X = np.array(train_X)/255.0
train_X = train_X.reshape(-1,28,28,1)
train_Y = np.array(train_Y)


[[1 0 0]
 [1 0 0]
 [0 1 0]
 ...
 [1 0 0]
 [0 1 0]
 [0 1 0]]
[[[[0.01568627]
   [0.01568627]
   [0.03137255]
   ...
   [0.43921569]
   [0.35686275]
   [0.36470588]]

  [[0.01568627]
   [0.01568627]
   [0.02352941]
   ...
   [0.6       ]
   [0.3254902 ]
   [0.35294118]]

  [[0.01568627]
   [0.01568627]
   [0.01960784]
   ...
   [0.73333333]
   [0.31372549]
   [0.25098039]]

  ...

  [[0.02352941]
   [0.02352941]
   [0.02745098]
   ...
   [0.03137255]
   [0.02352941]
   [0.03137255]]

  [[0.02352941]
   [0.03137255]
   [0.05882353]
   ...
   [0.01176471]
   [0.01568627]
   [0.03137255]]

  [[0.02745098]
   [0.03529412]
   [0.00392157]
   ...
   [0.0627451 ]
   [0.03137255]
   [0.03137255]]]


 [[[0.14509804]
   [0.15294118]
   [0.16862745]
   ...
   [0.17647059]
   [0.11372549]
   [0.10588235]]

  [[0.14509804]
   [0.15294118]
   [0.16862745]
   ...
   [0.29803922]
   [0.16862745]
   [0.12941176]]

  [[0.14509804]
   [0.15294118]
   [0.16470588]
   ...
   [0.35686275]
   [0.2       ]
   [

In [50]:


val_X = np.array(val_X)/255.0
val_X = val_X.reshape(-1,28,28,1)
val_Y = np.array(val_Y)

In [51]:
test_X = np.array(test_X)/255.0
test_X = val_X.reshape(-1,28,28,1)
test_Y = np.array(test_Y)

In [53]:


model = Sequential()

model.add(Conv2D(32, (3, 3), padding = "same", activation='relu', input_shape=(28,28,1)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3, activation='softmax'))



In [54]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_6 (Conv2D)           (None, 28, 28, 32)        320       
                                                                 
 max_pooling2d_6 (MaxPooling  (None, 14, 14, 32)       0         
 2D)                                                             
                                                                 
 conv2d_7 (Conv2D)           (None, 12, 12, 64)        18496     
                                                                 
 max_pooling2d_7 (MaxPooling  (None, 6, 6, 64)         0         
 2D)                                                             
                                                                 
 conv2d_8 (Conv2D)           (None, 4, 4, 128)         73856     
                                                                 
 max_pooling2d_8 (MaxPooling  (None, 2, 2, 128)       

In [55]:
model.compile(loss='categorical_crossentropy', optimizer="adam",metrics=['accuracy'])

In [56]:
history = model.fit(train_X,train_Y, epochs=20, batch_size=32, validation_data = (val_X, val_Y),  verbose=1)

Epoch 1/20
360/360 [==============================] - 14s 37ms/step - loss: 0.2059 - accuracy: 0.9080 - val_loss: 0.0241 - val_accuracy: 0.9944
Epoch 2/20
360/360 [==============================] - 12s 32ms/step - loss: 0.0228 - accuracy: 0.9932 - val_loss: 0.0163 - val_accuracy: 0.9951
Epoch 3/20
360/360 [==============================] - 11s 31ms/step - loss: 0.0184 - accuracy: 0.9948 - val_loss: 0.0060 - val_accuracy: 0.9988
Epoch 4/20
360/360 [==============================] - 11s 31ms/step - loss: 0.0093 - accuracy: 0.9970 - val_loss: 0.0018 - val_accuracy: 0.9994
Epoch 5/20
360/360 [==============================] - 11s 30ms/step - loss: 0.0065 - accuracy: 0.9983 - val_loss: 0.0012 - val_accuracy: 0.9997
Epoch 6/20
360/360 [==============================] - 11s 30ms/step - loss: 0.0073 - accuracy: 0.9974 - val_loss: 0.0060 - val_accuracy: 0.9978
Epoch 7/20
360/360 [==============================] - 11s 30ms/step - loss: 0.0064 - accuracy: 0.9977 - val_loss: 0.0035 - val_accuracy:

In [57]:
model.save('model_interview/model_interview.h5')

In [59]:
prediction=model.predict(test_X)
for i in range(100):
    
    print(prediction[i])
    print(test_Y[i])
    probabilityValue=np.amax(prediction[i])
    print(probabilityValue*100)

102/102 [==============================] - 1s 9ms/step
[1.0000000e+00 8.1141740e-23 3.1530962e-21]
[1 0 0]
100.0
[1.0000000e+00 1.2612709e-09 2.5469113e-11]
[1 0 0]
100.0
[7.1738973e-12 1.0000000e+00 9.7038029e-12]
[0 1 0]
100.0
[1.0159840e-15 1.0000000e+00 1.5648592e-15]
[0 1 0]
100.0
[1.0000000e+00 4.7643410e-11 1.6275757e-14]
[1 0 0]
100.0
[1.0000000e+00 1.1833201e-10 1.4132480e-14]
[1 0 0]
100.0
[1.0000000e+00 4.1562191e-16 4.5828616e-15]
[1 0 0]
100.0
[1.0000000e+00 7.2798884e-14 6.9647432e-15]
[1 0 0]
100.0
[1.000000e+00 5.221467e-23 2.442610e-21]
[1 0 0]
100.0
[1.1300045e-10 4.2947175e-08 1.0000000e+00]
[0 0 1]
100.0
[4.7106656e-08 1.0000000e+00 7.4622100e-11]
[0 1 0]
100.0
[1.4126395e-13 1.0000000e+00 7.9096292e-15]
[0 1 0]
100.0
[1.0000000e+00 1.3559777e-24 3.9784262e-22]
[1 0 0]
100.0
[7.9543316e-12 1.0000000e+00 2.9538007e-13]
[0 1 0]
100.0
[1.1543119e-09 1.0000000e+00 3.2047691e-12]
[0 1 0]
100.0
[6.0877944e-15 1.0000000e+00 2.3180402e-13]
[0 1 0]
100.0
[4.6192907e-11 1.203

In [60]:
def process(imgg):
    imgg = cv2.resize(imgg,(28,28))
    test_x=[]
    test_x.append(imgg)
    test_x = np.array(test_x)/255.0
    test_x = test_x.reshape(-1,28,28,1)
    prediction=model.predict_classes(test_x)
    prob=np.amax(predictions[i])
    print(prob*100)
    print(prediction)
    return prediction

    